version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: elasticsearch
    privileged: true #赋予这个容器的root权限
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./es/data:/usr/share/elasticsearch/data  #数据文件挂载
      - ./es/logs:/usr/share/elasticsearch/logs  #日志挂载
      - ./es/plugins:/usr/share/elasticsearch/plugins  #插件文件挂载
    environment:
      - "node.name=elasticsearch"
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
      - "xpack.security.enabled=false"  #关闭xpack认证
    labels:
      org.springframework.boot.service-connection: elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    container_name: kibana
    privileged: true
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
      # - elasticsearch.username="kibana_system"
      # - elasticsearch.password="123"
      - "xpack.management.enabled=false"
      - "i18n.local=zh-CN"
    ports:
      - "5601:5601"

  logstash:
     image: docker.elastic.co/logstash/logstash:8.9.1
     container_name: logstash
     privileged: true
     volumes:
       - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
     depends_on:
       - elasticsearch
     links:
       - elasticsearch:es
     environment:
       - "xpack.management.enabled=false"
       - "xpack.monitoring.elasticsearch.hosts= http://es:9200"
     ports:
       - "4560:4560"

#  fluentd:
#    image: fluent/fluentd:latest
#    container_name: fluentd
#    volumes:
#      - /Users/chenning/dockerCompose/mydata/fluentd/log:/fluentd/log
#      - /Users/chenning/dockerCompose/mydata/fluentd/fluent.conf:/fluentd/etc/fluent.conf
#    depends_on:
#      - elasticsearch
#    links:
#      - elasticsearch:es
#    ports:
#      - "24224:24224"

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:8.9.1
  #   container_name: filebeat
  #   links:
  #     - elasticsearch:es
  #   depends_on:
  #     - elasticsearch
  #     - kibana
  #   environment:
  #     - "output.elasticsearch.hosts=http://es:9200"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    labels:
      org.springframework.boot.service-connection: redis

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    privileged: true
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      org.springframework.boot.service-connection: rabbitmq