spring:
  profiles:
    active: dev

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'

  mail:
    host: smtp.qq.com
    username: 531237716@qq.com
    password: ENC(i4zMO8N0ihz2sXZtcCMoDXId6gEW2xH4uv6p01hPxtCYm+aCZIfD9I26MQKkB2tIZiRGXg5aiP+slVPS+rMKhg==)
    default-encoding: UTF-8

  thymeleaf:
    cache: false
    encoding: UTF-8
    enable-spring-el-compiler: true

  cache:
    type: redis

#  redis:
#    #集群模式
#    cluster:
#      nodes: 192.168.177.128:7001,192.168.177.128:7002,192.168.177.128:7003,192.168.177.128:7004,192.168.177.128:7005,192.168.177.128:7006
#      max-redirects: 3
#    #哨兵模式
#    sentinel:
#      master: mymaster
#      nodes: 127.0.0.1:26379,127.0.0.1:26479

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
#        wall:
#          enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        profile-enable: true
        session-stat-enable: true
        session-stat-max-count: 100000
      aop-patterns: 'com.cn.*'
      stat-view-servlet:
        enabled: true
        url-pattern: '/druid/*'
        reset-enable: true
#        login-username: 123456
#        login-password: admin


oss:
  config:
    host: https://oss-cn-hongkong-internal.aliyuncs.com
    bucket-name: music-story
    access-key-id: ENC(BFmGqMfhERt8BVG81BuQFAI4L165TxyjahwvlTGx9QnjkKAWytNvhhtfiajw1mhsGTLh5JErMOFrjltogIkOUg==)
    access-key-secret: ENC(Ng+yTJPV6RPseJCbuVbk2vqwElnl5fdddl22TAYCvyOVoHSjINi9Tk01j+8CLmozS/ysp3gWFbU5Ock4znKENw==)
    endpoint: oss.ngcly.cn
