server:
  port: 9090
  servlet:
    session:
      timeout: 1800

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music_story?serverTimezone=UTC&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: true
      file: docker-compose.yml